name: Hello World
on:
  push:
    branches: [ "main" ]

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Echo text
        run: echo "Hello, world!"

     
